kind: pipeline
type: docker
name: main-ci

trigger:
  event: push
  branch: feature/migrate-to-vitepress

steps:
  - name: npm install
    image: node:18.19
    commands:
      - node -v
      - npm -v
      - npm ci

  - name: Check prettier
    image: node:18.19
    commands:
      - npm run check-format

  - name: Vercel deploy to prod
    image: node:18.19
    environment:
      VERCEL_ORG_ID: team_qEUZmPwX3J0FFDAk23fSvIlq
      VERCEL_PROJECT_ID: prj_XD11Fr78qNrfVoaAa46D1iAvIQIT
      VERCEL_TOKEN:
        from_secret: vercel-token
    commands:
      - npm install --global vercel@canary
      - vercel pull --yes --environment=production --scope i-exec --token $VERCEL_TOKEN
      - SET_SUBPATH_FOR_PROD=true VITE_APP_COMMIT=${DRONE_COMMIT} vercel build --prod --scope i-exec --token $VERCEL_TOKEN
      - vercel deploy --prod --prebuilt --scope i-exec --token $VERCEL_TOKEN
